sudo: false
dist: trusty
language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: beta
    - rust: stable
  fast_finish: true

script:
  - cargo build --all --release
  - cargo test --verbose --all --release
